Проектная работа №12. Проект по темам: серверная разработка на Node.js, введение в express.js.
YuliaPotapova/product_12.github.io pull request #1
Opened 2020-05-07 18:56 UTC by YuliaPotapova

В рамках данного проекта:
- посредством фреймворка express организован локальный сервер;
- созданы роуты для обработки нескольких запросов (в том числе динамический роут);
- в коде применён мидлвэр;
- организована отдача статичных файлов (файлы разметки, стилей, скрипты, изображения);
- серверный код разбит на модули, объединённые системой экспорта/импорта.

2020-05-07 19:26 UTC, mrprovoker requested changes
Добрый день!

Очень хорошая работа!

Отдельно стоит отметить:
- нет ошибок линтера;
- хорошо оформлен README;
- код чистый, структура проекта логичная;

---
### **Надо исправить:**
- Ошибка при запросе: PATCH `http://localhost:3000/cards`. **Ответ не соответствует ожидаемому.**
   По заданию ожидается:
   ```json
   {"message":"Запрашиваемый ресурс не найден"}
   ```
   Фактически приложение отвечает:
   ```html
   <!DOCTYPE html>
   <html lang="en">
   <head>
   <meta charset="utf-8">
   <title>Error</title>
   </head>
   <body>
   <pre>Cannot PATCH /cards</pre>
   </body>
   </html>
   
   ```


- Ошибка при запросе: POST `http://localhost:3000/users`. **Ответ не соответствует ожидаемому.**
   По заданию ожидается:
   ```json
   {"message":"Запрашиваемый ресурс не найден"}
   ```
   Фактически приложение отвечает:
   ```html
   <!DOCTYPE html>
   <html lang="en">
   <head>
   <meta charset="utf-8">
   <title>Error</title>
   </head>
   <body>
   <pre>Cannot POST /users</pre>
   </body>
   </html>
   
   ```


- Ошибка при запросе: DELETE `http://localhost:3000/users/dbfe53c3c4d568240378b0c6`. **Ответ не соответствует ожидаемому.**
   По заданию ожидается:
   ```json
   {"message":"Запрашиваемый ресурс не найден"}
   ```
   Фактически приложение отвечает:
   ```html
   <!DOCTYPE html>
   <html lang="en">
   <head>
   <meta charset="utf-8">
   <title>Error</title>
   </head>
   <body>
   <pre>Cannot DELETE /users/dbfe53c3c4d568240378b0c6</pre>
   </body>
   </html>
   
   ```


- Ошибка при запросе: POST `http://localhost:3000/unknown-path`. **Ответ не соответствует ожидаемому.**
   По заданию ожидается:
   ```json
   {"message":"Запрашиваемый ресурс не найден"}
   ```
   Фактически приложение отвечает:
   ```html
   <!DOCTYPE html>
   <html lang="en">
   <head>
   <meta charset="utf-8">
   <title>Error</title>
   </head>
   <body>
   <pre>Cannot POST /unknown-path</pre>
   </body>
   </html>
   
   ```
- Для исправления предыдущих ошибок рекомендую подробнее прочитать про маршрутизацию различных видов запросов, например в [официальной документации](https://expressjs.com/ru/guide/routing.html). Предлагаю обратить внимание на метод `all`. 
- Зачем в routerOther дополнительно парсится путь?
- В репозитории есть директория, не относящаяся к проекту - `.vscode`. Аналогично директория `.vs`. Таких файлов в репозитории не должно быть, данные файлы обычно перечисляются в .gitignore.
- Писать таким образом (дублировать роуты):
   ```js
   routUsers.get('/:id', doesUserExist);
   routUsers.get(':id', (req, res) => ...);
   ```
   не принято. 
   Сейчас функция doesUserExist выглядит как так называемая middleware. Они указываются перед обработчиками, то есть вот так: 
   ```js
   routUsers.get('/users/:id', doesUserExist, (req, res) => ...);
   ```


### *Можно лучше:*
- В файле `package.json` рекомендуется заполнить секцию **description**.
Подробнее про секцию можно прочитать в официальной документации [по данной ссылке.](https://nodejs.dev/the-package-json-guide#description)

- Рекомендую обратить вниманиме на метод `find` у массивов (вместо `filter`).

- Обычно файл `README.md` называют заглавными буквами.

---
**Важно:** при правках данный *pull request* закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же *pull request*'е.

Исправление замечаний из пункта *можно лучше* крайне приветствуется.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-05-08 17:25 UTC, YuliaPotapova commented
Добрый вечер!
Все замечания устранила.
Файл README.md переименовала большими буквами, но после отправки коммита на гитхаб оказалось, что он тут всё равно почему-то остался маленькими буквами написан :\

2020-05-09 08:19 UTC, mrprovoker approved these changes
Спасибо за правки. Теперь работа отличная.


Небольшие рекомендации из пункта *можно лучше*, которые крайне приветствуется исправить перед мержем данного пулл реквеста:
- В репозитории [остались](https://github.com/YuliaPotapova/product_12.github.io/tree/develop) директории, не относящаяся к проекту - `.vscode` и `.vs`. Нужно их удалить и закоммитить данные изменения (просто удалить будет недостаточно).

---
Все пункты задания выполнены в полном объеме. Задание **принято** 👍

*Желаю успехов в дальнейшем обучении!*

2020-05-09 08:19 UTC, mrprovoker commented on package.json
> +  "description": "��������� ������ �� �����: ��������� ���������� �� Node.js, �������� � express.js",
Можно лучше:
- Чтобы корректно отображались символы - файл должен быть в кодировке UTF-8

2020-05-09 09:47 UTC, merged